packages:
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: false
  nx: true
  unrs-resolver: false

catalog:
  'react-compiler-runtime': '1.0.0'
  '@react-spring/web': '^10'
minimumReleaseAge: 10080 # 7 days
overrides:
  playwright: ^1.58.2
