packages:
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  esbuild: true
  msw: false
  nx: true
  unrs-resolver: false

catalog:
  autoprefixer: 10.5.4
  '@testing-library/jest-dom': '6.9.1'
  '@testing-library/react': '16.3.2'
  '@testing-library/user-event': '14.6.1'
  'react-compiler-runtime': '1.0.0'
  '@react-spring/web': '^10'
  postcss: '8.5.19'
  postcss-selector-parser: '7.1.4'
  react-aria: '3.50.0'
  react-stately: '3.48.0'

minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeExclude:
  - '@pixiv/eslint-config'
overrides:
  playwright: ^1.58.2
