import { TailwindBuild } from './_lib/TailwindBuild'
import { unstable_createTailwindConfigTokenV2 } from './tokenV2'
import { getTokenV2TailwindClassMappings } from './tokenV2Mappings'

describe('getTokenV2TailwindClassMappings', async () => {
  const mappings = getTokenV2TailwindClassMappings()

  test('returns the recommended color mappings', () => {
    expect(mappings).toMatchSnapshot()
  })

  test('omits DEFAULT from class names', () => {
    expect(
      getTokenV2TailwindClassMappings({
        tokens: ['color.container.primary.default'],
        includeCssVariable: true,
        includeThemeValue: true,
      }),
    ).toEqual([
      {
        tokenPath: 'color.container.primary.default',
        cssVariable: '--charcoal-color-container-primary-default',
        sourceTokens: [
          {
            tokenPath: 'color.container.primary.default',
            cssVariable: '--charcoal-color-container-primary-default',
          },
        ],
        themeEntries: [
          {
            themePath: 'colors.container.primary.DEFAULT',
            themeValue: 'var(--charcoal-color-container-primary-default)',
          },
        ],
        classCandidates: [
          {
            className: 'bg-container-primary',
            utility: 'backgroundColor',
            cssProperties: ['background-color'],
          },
        ],
        category: 'color',
        source: 'token-v2',
        mappingKind: 'recommended',
      },
    ])
  })

  test('returns both theme entries for border colors', () => {
    const [mapping] = getTokenV2TailwindClassMappings({
      tokens: ['color.border.secondary'],
    })

    expect(mapping).toMatchObject({
      category: 'borderColor',
      themeEntries: [
        { themePath: 'borderColor.ch-secondary' },
        { themePath: 'colors.border.secondary' },
      ],
      classCandidates: [
        {
          className: 'border-ch-secondary',
          utility: 'borderColor',
          cssProperties: ['border-color'],
        },
      ],
    })
  })

  test('filters mappings and candidates independently', () => {
    expect(
      getTokenV2TailwindClassMappings({
        categories: ['color'],
        utilities: ['stroke'],
        tokens: ['color.icon.default', 'color.border.default'],
      }),
    ).toEqual([
      expect.objectContaining({
        tokenPath: 'color.icon.default',
        classCandidates: [
          {
            className: 'stroke-icon',
            utility: 'stroke',
            cssProperties: ['stroke'],
          },
        ],
      }),
    ])
  })

  test('can select one candidate for ambiguous icon colors', () => {
    expect(
      getTokenV2TailwindClassMappings({
        tokens: ['color.icon.default'],
        includeAmbiguousUtilities: false,
      })[0].classCandidates,
    ).toEqual([
      {
        className: 'fill-icon',
        utility: 'fill',
        cssProperties: ['fill'],
      },
    ])
  })

  test('maps matching font-size and line-height tokens to one class', () => {
    const [mapping] = getTokenV2TailwindClassMappings({
      tokens: ['text.line-height.heading.s'],
      includeCssVariable: true,
      includeThemeValue: true,
    })

    expect(mapping).toEqual({
      tokenPath: 'text.font-size.heading.s',
      cssVariable: '--charcoal-text-font-size-heading-s',
      sourceTokens: [
        {
          tokenPath: 'text.font-size.heading.s',
          cssVariable: '--charcoal-text-font-size-heading-s',
        },
        {
          tokenPath: 'text.line-height.heading.s',
          cssVariable: '--charcoal-text-line-height-heading-s',
        },
      ],
      themeEntries: [
        {
          themePath: 'fontSize.heading-s',
          themeValue: [
            'var(--charcoal-text-font-size-heading-s)',
            { lineHeight: 'var(--charcoal-text-line-height-heading-s)' },
          ],
        },
      ],
      classCandidates: [
        {
          className: 'text-heading-s',
          utility: 'fontSize',
          cssProperties: ['font-size', 'line-height'],
        },
      ],
      category: 'text',
      source: 'token-v2',
      mappingKind: 'recommended',
    })
  })

  test('all recommended classes can be generated by the token v2 preset', async () => {
    const result = await TailwindBuild.run(
      // @ts-expect-error TailwindBuild supplies content through its safelist
      unstable_createTailwindConfigTokenV2(),
      `
        @import 'tailwindcss/base';
        @import 'tailwindcss/utilities';
        @import 'tailwindcss/components';
      `,
    )
    const generatedClasses = new Set(result.classNames)

    for (const { classCandidates } of mappings) {
      for (const { className } of classCandidates) {
        expect(generatedClasses.has(className), className).toBe(true)
      }
    }
  })
})
