/** This file is auto generated. DO NOT EDIT BY HAND. */

declare var _default: {
  '16/Add': { uri: string; isSetCurrentcolor: boolean }
  '16/Archive': { uri: string; isSetCurrentcolor: boolean }
  '16/ArrowDown': { uri: string; isSetCurrentcolor: boolean }
  '16/Artwork': { uri: string; isSetCurrentcolor: boolean }
  '16/Back': { uri: string; isSetCurrentcolor: boolean }
  '16/Book': { uri: string; isSetCurrentcolor: boolean }
  '16/BookmarkOff': { uri: string; isSetCurrentcolor: boolean }
  '16/BookmarkOn': { uri: string; isSetCurrentcolor: boolean }
  '16/Check': { uri: string; isSetCurrentcolor: boolean }
  '16/Comment': { uri: string; isSetCurrentcolor: boolean }
  '16/Dot': { uri: string; isSetCurrentcolor: boolean }
  '16/Error': { uri: string; isSetCurrentcolor: boolean }
  '16/Filter': { uri: string; isSetCurrentcolor: boolean }
  '16/ImageResponse': { uri: string; isSetCurrentcolor: boolean }
  '16/Info': { uri: string; isSetCurrentcolor: boolean }
  '16/Like': { uri: string; isSetCurrentcolor: boolean }
  '16/Menu': { uri: string; isSetCurrentcolor: boolean }
  '16/More': { uri: string; isSetCurrentcolor: boolean }
  '16/Nextworks': { uri: string; isSetCurrentcolor: boolean }
  '16/Pencil': { uri: string; isSetCurrentcolor: boolean }
  '16/Question': { uri: string; isSetCurrentcolor: boolean }
  '16/Ranking': { uri: string; isSetCurrentcolor: boolean }
  '16/Remove': { uri: string; isSetCurrentcolor: boolean }
  '16/Search': { uri: string; isSetCurrentcolor: boolean }
  '16/Smile': { uri: string; isSetCurrentcolor: boolean }
  '16/Speaker': { uri: string; isSetCurrentcolor: boolean }
  '16/View': { uri: string; isSetCurrentcolor: boolean }
  '16/Warning': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Add': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Back': { uri: string; isSetCurrentcolor: boolean }
  'Inline/BookmarkOff': { uri: string; isSetCurrentcolor: boolean }
  'Inline/BookmarkOn': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Breadcrumbs': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Check': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Comment': { uri: string; isSetCurrentcolor: boolean }
  'Inline/ContextMenu': { uri: string; isSetCurrentcolor: boolean }
  'Inline/External': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Filter': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Folder': { uri: string; isSetCurrentcolor: boolean }
  'Inline/ImageResponse': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Images': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Latest': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Like': { uri: string; isSetCurrentcolor: boolean }
  'Inline/LikeOff': { uri: string; isSetCurrentcolor: boolean }
  'Inline/List': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Location': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Lock': { uri: string; isSetCurrentcolor: boolean }
  'Inline/More': { uri: string; isSetCurrentcolor: boolean }
  'Inline/MultiSelect': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Nextworks': { uri: string; isSetCurrentcolor: boolean }
  'Inline/OpenInNew': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Pencil': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Remove': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Smile': { uri: string; isSetCurrentcolor: boolean }
  'Inline/SmileOn': { uri: string; isSetCurrentcolor: boolean }
  'Inline/Users': { uri: string; isSetCurrentcolor: boolean }
  'Inline/View': { uri: string; isSetCurrentcolor: boolean }
  'Inline/ViewOutline': { uri: string; isSetCurrentcolor: boolean }
  '32/BookmarkOff': { uri: string; isSetCurrentcolor: boolean }
  '32/BookmarkOn': { uri: string; isSetCurrentcolor: boolean }
  '32/Camera': { uri: string; isSetCurrentcolor: boolean }
  '32/Close': { uri: string; isSetCurrentcolor: boolean }
  '32/Collapse': { uri: string; isSetCurrentcolor: boolean }
  '32/CommentOff': { uri: string; isSetCurrentcolor: boolean }
  '32/CommentOn': { uri: string; isSetCurrentcolor: boolean }
  '32/Delete': { uri: string; isSetCurrentcolor: boolean }
  '32/Dot': { uri: string; isSetCurrentcolor: boolean }
  '32/Edit': { uri: string; isSetCurrentcolor: boolean }
  '32/Expand': { uri: string; isSetCurrentcolor: boolean }
  '32/Gift': { uri: string; isSetCurrentcolor: boolean }
  '32/Home': { uri: string; isSetCurrentcolor: boolean }
  '32/HorizontalWriting': { uri: string; isSetCurrentcolor: boolean }
  '32/ImageHidden': { uri: string; isSetCurrentcolor: boolean }
  '32/Index': { uri: string; isSetCurrentcolor: boolean }
  '32/LikeOff': { uri: string; isSetCurrentcolor: boolean }
  '32/LikeOn': { uri: string; isSetCurrentcolor: boolean }
  '32/LikeOnPrivate': { uri: string; isSetCurrentcolor: boolean }
  '32/Message': { uri: string; isSetCurrentcolor: boolean }
  '32/Next': { uri: string; isSetCurrentcolor: boolean }
  '32/Notification': { uri: string; isSetCurrentcolor: boolean }
  '32/NotificationOff': { uri: string; isSetCurrentcolor: boolean }
  '32/NovelViewerSettings': { uri: string; isSetCurrentcolor: boolean }
  '32/Pan': { uri: string; isSetCurrentcolor: boolean }
  '32/Prev': { uri: string; isSetCurrentcolor: boolean }
  '32/PullDown': { uri: string; isSetCurrentcolor: boolean }
  '32/PullUp': { uri: string; isSetCurrentcolor: boolean }
  '32/ReadHorizontalLeft': { uri: string; isSetCurrentcolor: boolean }
  '32/ReadHorizontalRight': { uri: string; isSetCurrentcolor: boolean }
  '32/ReadVertical': { uri: string; isSetCurrentcolor: boolean }
  '32/Redo': { uri: string; isSetCurrentcolor: boolean }
  '32/RollHorizontal': { uri: string; isSetCurrentcolor: boolean }
  '32/RollVertical': { uri: string; isSetCurrentcolor: boolean }
  '32/SansSerif': { uri: string; isSetCurrentcolor: boolean }
  '32/Serif': { uri: string; isSetCurrentcolor: boolean }
  '32/ShareAndroid': { uri: string; isSetCurrentcolor: boolean }
  '32/ShareIos': { uri: string; isSetCurrentcolor: boolean }
  '32/Shopping': { uri: string; isSetCurrentcolor: boolean }
  '32/Undo': { uri: string; isSetCurrentcolor: boolean }
  '32/Upload': { uri: string; isSetCurrentcolor: boolean }
  '32/User': { uri: string; isSetCurrentcolor: boolean }
  '32/VerticalWriting': { uri: string; isSetCurrentcolor: boolean }
  '32/ZoomIn': { uri: string; isSetCurrentcolor: boolean }
  '24/Add': { uri: string; isSetCurrentcolor: boolean }
  '24/AddImage': { uri: string; isSetCurrentcolor: boolean }
  '24/AddModel': { uri: string; isSetCurrentcolor: boolean }
  '24/AddPeople': { uri: string; isSetCurrentcolor: boolean }
  '24/AddRubi': { uri: string; isSetCurrentcolor: boolean }
  '24/AddText': { uri: string; isSetCurrentcolor: boolean }
  '24/Alart': { uri: string; isSetCurrentcolor: boolean }
  '24/Announcement': { uri: string; isSetCurrentcolor: boolean }
  '24/Ar': { uri: string; isSetCurrentcolor: boolean }
  '24/Archive': { uri: string; isSetCurrentcolor: boolean }
  '24/ArrowDown': { uri: string; isSetCurrentcolor: boolean }
  '24/ArrowUp': { uri: string; isSetCurrentcolor: boolean }
  '24/Binet': { uri: string; isSetCurrentcolor: boolean }
  '24/Body': { uri: string; isSetCurrentcolor: boolean }
  '24/BodyEdit': { uri: string; isSetCurrentcolor: boolean }
  '24/Book': { uri: string; isSetCurrentcolor: boolean }
  '24/BringBackward': { uri: string; isSetCurrentcolor: boolean }
  '24/BringForward': { uri: string; isSetCurrentcolor: boolean }
  '24/Calendar': { uri: string; isSetCurrentcolor: boolean }
  '24/Camera': { uri: string; isSetCurrentcolor: boolean }
  '24/CameraVideo': { uri: string; isSetCurrentcolor: boolean }
  '24/Cart': { uri: string; isSetCurrentcolor: boolean }
  '24/ChangeCharacter': { uri: string; isSetCurrentcolor: boolean }
  '24/ChatBot': { uri: string; isSetCurrentcolor: boolean }
  '24/Check': { uri: string; isSetCurrentcolor: boolean }
  '24/ChromaticAberration': { uri: string; isSetCurrentcolor: boolean }
  '24/Click': { uri: string; isSetCurrentcolor: boolean }
  '24/Close': { uri: string; isSetCurrentcolor: boolean }
  '24/Codes': { uri: string; isSetCurrentcolor: boolean }
  '24/Collapse': { uri: string; isSetCurrentcolor: boolean }
  '24/Collection': { uri: string; isSetCurrentcolor: boolean }
  '24/CommentFill': { uri: string; isSetCurrentcolor: boolean }
  '24/CommentOutline': { uri: string; isSetCurrentcolor: boolean }
  '24/Contest': { uri: string; isSetCurrentcolor: boolean }
  '24/Contrast': { uri: string; isSetCurrentcolor: boolean }
  '24/Description': { uri: string; isSetCurrentcolor: boolean }
  '24/DeviceRotation': { uri: string; isSetCurrentcolor: boolean }
  '24/Discovery': { uri: string; isSetCurrentcolor: boolean }
  '24/Dot': { uri: string; isSetCurrentcolor: boolean }
  '24/DotAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Down': { uri: string; isSetCurrentcolor: boolean }
  '24/DownloadAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Duplicate': { uri: string; isSetCurrentcolor: boolean }
  '24/Dust': { uri: string; isSetCurrentcolor: boolean }
  '24/Emoji': { uri: string; isSetCurrentcolor: boolean }
  '24/Error': { uri: string; isSetCurrentcolor: boolean }
  '24/ErrorOctagon': { uri: string; isSetCurrentcolor: boolean }
  '24/Events': { uri: string; isSetCurrentcolor: boolean }
  '24/Expand': { uri: string; isSetCurrentcolor: boolean }
  '24/FaceEdit': { uri: string; isSetCurrentcolor: boolean }
  '24/Fashion': { uri: string; isSetCurrentcolor: boolean }
  '24/Feed': { uri: string; isSetCurrentcolor: boolean }
  '24/File': { uri: string; isSetCurrentcolor: boolean }
  '24/Filter': { uri: string; isSetCurrentcolor: boolean }
  '24/Flare': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatAlignCenter': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatAlignJustified': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatAlignLeft': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatAlignRight': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatColorFill': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatColorFillNoColor': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatFontFamily': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatFontSize': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatLetterSpacing': { uri: string; isSetCurrentcolor: boolean }
  '24/FormatLineSpacing': { uri: string; isSetCurrentcolor: boolean }
  '24/Fov': { uri: string; isSetCurrentcolor: boolean }
  '24/FrameEffect': { uri: string; isSetCurrentcolor: boolean }
  '24/FrameSize': { uri: string; isSetCurrentcolor: boolean }
  '24/Gift': { uri: string; isSetCurrentcolor: boolean }
  '24/Glow': { uri: string; isSetCurrentcolor: boolean }
  '24/Groups': { uri: string; isSetCurrentcolor: boolean }
  '24/HairEdit': { uri: string; isSetCurrentcolor: boolean }
  '24/Hashtag': { uri: string; isSetCurrentcolor: boolean }
  '24/Hide': { uri: string; isSetCurrentcolor: boolean }
  '24/HightlightText': { uri: string; isSetCurrentcolor: boolean }
  '24/Home': { uri: string; isSetCurrentcolor: boolean }
  '24/Hue': { uri: string; isSetCurrentcolor: boolean }
  '24/Idea': { uri: string; isSetCurrentcolor: boolean }
  '24/Image': { uri: string; isSetCurrentcolor: boolean }
  '24/ImageAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/ImageHidden': { uri: string; isSetCurrentcolor: boolean }
  '24/ImageReplace': { uri: string; isSetCurrentcolor: boolean }
  '24/Images': { uri: string; isSetCurrentcolor: boolean }
  '24/ImgContain': { uri: string; isSetCurrentcolor: boolean }
  '24/ImgCover': { uri: string; isSetCurrentcolor: boolean }
  '24/Index': { uri: string; isSetCurrentcolor: boolean }
  '24/Info': { uri: string; isSetCurrentcolor: boolean }
  '24/Invalid': { uri: string; isSetCurrentcolor: boolean }
  '24/Invoice': { uri: string; isSetCurrentcolor: boolean }
  '24/ItemRemove': { uri: string; isSetCurrentcolor: boolean }
  '24/LatestWorks': { uri: string; isSetCurrentcolor: boolean }
  '24/LikeOff': { uri: string; isSetCurrentcolor: boolean }
  '24/LikeOn': { uri: string; isSetCurrentcolor: boolean }
  '24/Link': { uri: string; isSetCurrentcolor: boolean }
  '24/List': { uri: string; isSetCurrentcolor: boolean }
  '24/LockLock': { uri: string; isSetCurrentcolor: boolean }
  '24/LockUnlock': { uri: string; isSetCurrentcolor: boolean }
  '24/Logout': { uri: string; isSetCurrentcolor: boolean }
  '24/Manga': { uri: string; isSetCurrentcolor: boolean }
  '24/Menu': { uri: string; isSetCurrentcolor: boolean }
  '24/Message': { uri: string; isSetCurrentcolor: boolean }
  '24/Microphone': { uri: string; isSetCurrentcolor: boolean }
  '24/MobilePhone': { uri: string; isSetCurrentcolor: boolean }
  '24/Move1': { uri: string; isSetCurrentcolor: boolean }
  '24/MultiSelect': { uri: string; isSetCurrentcolor: boolean }
  '24/Next': { uri: string; isSetCurrentcolor: boolean }
  '24/NoImage': { uri: string; isSetCurrentcolor: boolean }
  '24/Notification': { uri: string; isSetCurrentcolor: boolean }
  '24/NotificationOff': { uri: string; isSetCurrentcolor: boolean }
  '24/Novels': { uri: string; isSetCurrentcolor: boolean }
  '24/OpenInNew': { uri: string; isSetCurrentcolor: boolean }
  '24/Options': { uri: string; isSetCurrentcolor: boolean }
  '24/OptionsAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Overlay': { uri: string; isSetCurrentcolor: boolean }
  '24/Palette': { uri: string; isSetCurrentcolor: boolean }
  '24/Pause': { uri: string; isSetCurrentcolor: boolean }
  '24/PauseAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Pencil': { uri: string; isSetCurrentcolor: boolean }
  '24/PencilAdd': { uri: string; isSetCurrentcolor: boolean }
  '24/PencilDraw': { uri: string; isSetCurrentcolor: boolean }
  '24/PencilLive': { uri: string; isSetCurrentcolor: boolean }
  '24/PencilText': { uri: string; isSetCurrentcolor: boolean }
  '24/Person': { uri: string; isSetCurrentcolor: boolean }
  '24/Play': { uri: string; isSetCurrentcolor: boolean }
  '24/Pose': { uri: string; isSetCurrentcolor: boolean }
  '24/Prev': { uri: string; isSetCurrentcolor: boolean }
  '24/Projects': { uri: string; isSetCurrentcolor: boolean }
  '24/PullDown': { uri: string; isSetCurrentcolor: boolean }
  '24/PullUp': { uri: string; isSetCurrentcolor: boolean }
  '24/Question': { uri: string; isSetCurrentcolor: boolean }
  '24/QuestionOutline': { uri: string; isSetCurrentcolor: boolean }
  '24/Ranking': { uri: string; isSetCurrentcolor: boolean }
  '24/ReadHorizontalLeft': { uri: string; isSetCurrentcolor: boolean }
  '24/ReadHorizontalRight': { uri: string; isSetCurrentcolor: boolean }
  '24/ReadVertical': { uri: string; isSetCurrentcolor: boolean }
  '24/Redo': { uri: string; isSetCurrentcolor: boolean }
  '24/Reload': { uri: string; isSetCurrentcolor: boolean }
  '24/ReloadLoop': { uri: string; isSetCurrentcolor: boolean }
  '24/Reorder': { uri: string; isSetCurrentcolor: boolean }
  '24/Reply': { uri: string; isSetCurrentcolor: boolean }
  '24/Roll': { uri: string; isSetCurrentcolor: boolean }
  '24/Rotate90DegreesC': { uri: string; isSetCurrentcolor: boolean }
  '24/Rotate90DegreesCc': { uri: string; isSetCurrentcolor: boolean }
  '24/RotateRight': { uri: string; isSetCurrentcolor: boolean }
  '24/Saturation': { uri: string; isSetCurrentcolor: boolean }
  '24/Save': { uri: string; isSetCurrentcolor: boolean }
  '24/Search': { uri: string; isSetCurrentcolor: boolean }
  '24/Send': { uri: string; isSetCurrentcolor: boolean }
  '24/Services': { uri: string; isSetCurrentcolor: boolean }
  '24/Set': { uri: string; isSetCurrentcolor: boolean }
  '24/Settings': { uri: string; isSetCurrentcolor: boolean }
  '24/ShareAndroid': { uri: string; isSetCurrentcolor: boolean }
  '24/ShareIos': { uri: string; isSetCurrentcolor: boolean }
  '24/Shopping': { uri: string; isSetCurrentcolor: boolean }
  '24/Show': { uri: string; isSetCurrentcolor: boolean }
  '24/ShowOutline': { uri: string; isSetCurrentcolor: boolean }
  '24/Shutter': { uri: string; isSetCurrentcolor: boolean }
  '24/Star': { uri: string; isSetCurrentcolor: boolean }
  '24/Subtract': { uri: string; isSetCurrentcolor: boolean }
  '24/Sun': { uri: string; isSetCurrentcolor: boolean }
  '24/Temperature': { uri: string; isSetCurrentcolor: boolean }
  '24/Text': { uri: string; isSetCurrentcolor: boolean }
  '24/Thread': { uri: string; isSetCurrentcolor: boolean }
  '24/Trash': { uri: string; isSetCurrentcolor: boolean }
  '24/TrashAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Undo': { uri: string; isSetCurrentcolor: boolean }
  '24/Up': { uri: string; isSetCurrentcolor: boolean }
  '24/Upload': { uri: string; isSetCurrentcolor: boolean }
  '24/UploadAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Usagi': { uri: string; isSetCurrentcolor: boolean }
  '24/UsagiAlt': { uri: string; isSetCurrentcolor: boolean }
  '24/Users': { uri: string; isSetCurrentcolor: boolean }
  '24/Video': { uri: string; isSetCurrentcolor: boolean }
  '24/ViewGrid2Columns': { uri: string; isSetCurrentcolor: boolean }
  '24/ViewGrid3Columns': { uri: string; isSetCurrentcolor: boolean }
  '24/ViewList': { uri: string; isSetCurrentcolor: boolean }
  '24/Warning': { uri: string; isSetCurrentcolor: boolean }
}
export default _default
